### ISSUE TITLE
TODO-v1 før prod

### ISSUE THREAD

**Issue by Amirhlotfi** [navikt/tms-varsel-frontend#7]
```[tasklist]
### Tasks
- [ ] Legge til feilhåndtering 
- [ ] Legge inn visning for null varsler
- [ ] Håndtere isMasked
- [ ] Håndtere isMasked og hasMasked
- [ ] Håndtere isArkiverbar
- [ ] Håndtere varsler uten link
- [ ] Legge til skeleton ved fetch 
- [ ] Nytt endepunkt i BE i DEV
- [ ] Deploy til på dev
```
